- name: Instalar cliente MySQL para Python
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: Instalar AWS CLI
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Baixar AWS CLI v2
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Descompactar AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes

- name: Instalar AWS CLI
  command: /tmp/aws/install --update 