    - name: Instalar Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Login no ECR usando módulo Ansible
      community.docker.docker_login:
        registry_url: 829115578807.dkr.ecr.us-east-1.amazonaws.com
        username: AWS
        password: "{{ lookup('pipe', 'aws ecr get-login-password --region us-east-1') }}"


    - name: Garantir que container Flask esteja rodando
      community.docker.docker_container:
        name: flaskapp
        image: 829115578807.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
