- name: Criar diretório da aplicação
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Baixar aplicação do S3
  get_url:
    url: https://tbc-flask-app-deploy-bucket.s3.amazonaws.com/app.zip
    dest: /home/ubuntu/app.zip

- name: Extrair aplicação
  unarchive:
    src: /home/ubuntu/app.zip
    dest: /home/ubuntu/app/
    remote_src: yes
    owner: ubuntu
    group: ubuntu

- name: Criar virtualenv
  command: python3 -m venv /home/ubuntu/venv
  args:
    creates: /home/ubuntu/venv

- name: Instalar dependências no venv
  pip:
    requirements: /home/ubuntu/app/requirements.txt
    virtualenv: /home/ubuntu/venv

- name: Criar serviço systemd para a Flask app
  copy:
    dest: /etc/systemd/system/flaskapp.service
    content: |
      [Unit]
      Description=Flask App
      After=network.target

      [Service]
      User=ubuntu
      WorkingDirectory=/home/ubuntu/app
      ExecStart=/home/ubuntu/venv/bin/python3 /home/ubuntu/app/app.py
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

- name: Recarregar systemd
  systemd:
    daemon_reload: yes

- name: Habilitar e iniciar o serviço Flask
  systemd:
    name: flaskapp
    enabled: yes
    state: restarted
