name: CI/CD Infra + App

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_cidr_block: "10.0.0.0/16"
          TF_VAR_project_name: "terraform-tbc"
          TF_VAR_region: "us-east-1"
          TF_VAR_tags: '{"environment":"dev","Owner":"Igor Rodrigues"}'
          TF_VAR_ami_id: "ami-0b6d9d3d33ba97d99"
          TF_VAR_instance_type: "t3.micro"
          TF_VAR_allocated_storage: "10"
          TF_VAR_engine: "mysql"
          TF_VAR_engine_version: "8.0"
          TF_VAR_instance_class: "db.t3.micro"
          TF_VAR_db_name: "mydatabase"
          TF_VAR_username: "admin"
          TF_VAR_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_parameter_group_name: "default.mysql8.0"
          TF_VAR_publicly_accessible: "false"

  build-and-push:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login no ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS \
          --password-stdin 829115578807.dkr.ecr.us-east-1.amazonaws.com

      - name: Build da imagem
        run: docker build -t flaskapp:latest .

      - name: Tag da imagem
        run: docker tag flaskapp:latest 829115578807.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - name: Push para ECR
        run: docker push 829115578807.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Rodar playbook de deploy
        run: ansible-playbook -i ansible/hosts ansible/deploy.yml
